# apiVersion: apps/v1
# metadata:
#   name: test-deploy
#   namespace: default
#   labels: 
#     app: test
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: test
#   template:
#     metadata:
#       labels:
#         app: test
#     spec:
#       containers:
#       - name: nginx-app
#         image: nginx
#         imagePullPolicy: Always
#         resources:
#           requests:
#             cpu: 100m
#             memory: 256Mi
#           limits:
#             cpu: 150m
#             memory: 500Mi
#         ports:
#         - containerPort: 80
#           protocol: TCP
#     volumes:
#     - name: images
#       persistentVolumeClaim:
#         claimName: s3-images-us-west-2

# ---  

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mypv
#   namespace: default
# spec:
#   capacity:
#     storage: <Size>
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: slow
#   mountOptions:
#     - hard
#     - nfsvers=4.1
#   nfs:
#     path: /tmp
#     server: 172.17.0.2

